In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import warnings
warnings.filterwarnings("ignore")

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [2]:
df = pd.read_csv(
    "../dataset/processed/realestate_features.csv"
)

print("Dataset Loaded Successfully!")
print("Shape:", df.shape)

df.head()

Dataset Loaded Successfully!
Shape: (13859, 22)

,number_of_bedrooms,number_of_bathrooms,living_area,lot_area,number_of_floors,waterfront_present,number_of_views,condition_of_the_house,grade_of_the_house,house_area_without_basement,...,renovation_year,postal_code,lattitude,longitude,living_area_renov,lot_area_renov,number_of_schools_nearby,distance_from_the_airport,property_age,price
0,0.718714,0.610046,1.687492,0.746264,0.959757,-0.057075,-0.268014,-0.646877,1.383370,2.164078,...,-0.205387,-1.466558,1.165654,0.575773,2.269381,1.169110,1.210768,1.236614,-1.032690,838000
1,-0.366916,-0.094125,0.918413,-0.271116,0.029728,-0.057075,-0.268014,0.867493,0.423804,0.215045,...,-0.205387,-1.414054,0.819290,-0.571474,0.202462,-0.308117,-1.238336,-1.563202,1.428099,805000
2,-0.366916,0.610046,0.777415,-0.264509,-0.900300,-0.057075,-0.268014,0.867493,1.383370,-0.030288,...,-0.205387,-1.361550,0.880708,-1.305992,0.715186,-0.298486,-1.238336,0.228680,0.676191,790000
3,1.804345,1.666302,2.136121,-0.073047,0.959757,-0.057075,2.840277,-0.646877,2.342936,2.641113,...,-0.205387,-1.309045,-0.187665,2.471528,2.221313,-0.048436,1.210768,0.788643,-1.203578,785000
4,-0.366916,-0.446210,0.315967,-0.110494,0.959757,-0.057075,-0.268014,2.381862,0.423804,-0.234732,...,-0.205387,-1.414054,0.967120,-0.550488,-0.582647,-0.073976,1.210768,0.676651,1.633165,750000

In [3]:
X = df.drop(
    columns=["price"]
)

y = df["price"]


print("Features:", X.shape)
print("Target:", y.shape)

Features: (13859, 21)
Target: (13859,)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


print("Training samples:", X_train.shape)
print("Testing samples:", X_test.shape)

Training samples: (11087, 21)
Testing samples: (2772, 21)

In [5]:
# Linear Regression Model

lr_model = LinearRegression()

lr_model.fit(
    X_train,
    y_train
)

print("Linear Regression Training Completed!")

Linear Regression Training Completed!

In [6]:
# Predictions

lr_predictions = lr_model.predict(X_test)


# Evaluation

lr_mae = mean_absolute_error(
    y_test,
    lr_predictions
)

lr_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        lr_predictions
    )
)

lr_r2 = r2_score(
    y_test,
    lr_predictions
)


print("Linear Regression Results")
print("-------------------------")
print("MAE :", lr_mae)
print("RMSE:", lr_rmse)
print("R2 Score:", lr_r2)

Linear Regression Results
-------------------------
MAE : 83722.83234702848
RMSE: 111651.83199181948
R2 Score: 0.7159838817690902

In [7]:
# Random Forest Model

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)


rf_model.fit(
    X_train,
    y_train
)


print("Random Forest Training Completed!")

Random Forest Training Completed!

In [8]:
rf_predictions = rf_model.predict(
    X_test
)


rf_mae = mean_absolute_error(
    y_test,
    rf_predictions
)

rf_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        rf_predictions
    )
)

rf_r2 = r2_score(
    y_test,
    rf_predictions
)


print("Random Forest Results")
print("----------------------")
print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R2 Score:", rf_r2)

Random Forest Results
----------------------
MAE : 50957.244740259746
RMSE: 73725.81804528981
R2 Score: 0.8761629833774212

In [9]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest"
    ],
    "R2 Score": [
        lr_r2,
        rf_r2
    ],
    "RMSE": [
        lr_rmse,
        rf_rmse
    ],
    "MAE": [
        lr_mae,
        rf_mae
    ]
})


results

               Model  R2 Score           RMSE           MAE
0  Linear Regression  0.715984  111651.831992  83722.832347
1      Random Forest  0.876163   73725.818045  50957.244740

In [10]:
import os

os.makedirs(
    "../models",
    exist_ok=True
)

print("Models folder created!")

Models folder created!

In [11]:
import joblib


joblib.dump(
    rf_model,
    "../models/house_price_model.pkl"
)


print("Random Forest Model Saved Successfully!")

Random Forest Model Saved Successfully!

In [13]:
from sklearn.preprocessing import StandardScaler
import joblib

# Create scaler again
scaler = StandardScaler()

# Fit scaler on training data
scaler.fit(X_train)


# Save scaler
joblib.dump(
    scaler,
    "../models/scaler.pkl"
)

print("Scaler Saved Successfully!")

Scaler Saved Successfully!

In [14]:
import os

print(os.listdir("../models"))

['house_price_model.pkl', 'scaler.pkl']